# Generated by Django 4.1.7 on 2023-04-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predict', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
